friend1 = "Allan"
friend2 = "Joel"
friend3 = "Wes"
friend4 = "Shane"
friend3 = "Jon"
friends = "Allan", "Joel", "Wes", "Shane", "Jon"
length_of_friendship = [13.5, 14.2, 13.1, 38.2, 36.4]
code_name = "Brothers_by_choice"
puts code_name = "Brothers_by_choice"
